config/routes.rb
Rails.application.routes.draw do
  resources :bookings, only: [:index, :new, :create, :show] do
    collection do
      post :confirm
    end
  end
  
  get 'sessions/new'
  root 'pages#top'
  get "signup", to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :rooms do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :person, presence: true

  validate :date_before_start
  validate :start_end_check

  def date_before_start
    return if start_date.blank?
    if self.start_date < Date.today
      errors.add(:start_date, "は本日以降の日付でお願いします")
    end
  end

  def start_end_check
    return if end_date.blank? || start_date.blank?
    if self.end_date < self.start_date
      errors.add(:end_date, "は開始日以降の選択でお願いします")
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  mount_uploader :room_image, ImageUploader
  belongs_to :user
  has_many :bookings, dependent: :destroy

  validates :room_name, presence: true
  validates :description, presence: true
  validates :fee, presence: true
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :rooms
  has_many :bookings, dependent: :destroy
  
  mount_uploader :profile_image, ImageUploader
  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 1, maximum: 15 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :introduction, length:{ minimum: 4, maximum: 300 },
                            allow_nil: true
  has_secure_password
  validates :password, length: { minimum: 7 },
                       confirmation: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  before_action :configure_permitted_parameters , if: :devise_controller?
  before_action :set_q_for_room

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

  def set_q_for_room
    @q_header = Room.ransack(params[:q])
  end
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:profile_image])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @bookings = @user.bookings 
    if @bookings.present?
      @booking = current_user.bookings.last
      @room = @booking.room
    end
  end

  #def new
  #end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    if params[:back]
      @room = @booking.room
      @user = @room.user
      render "rooms/show"
    elsif @booking.save
      flash[:notice] = "新規予約を作成しました"
      redirect_to booking_path(@booking)
    else 
      flash[:notice] = "新規予約に失敗しました"
      render "pages/top"
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @room = @booking.room 
  end

  def confirm
    @room = Room.find(params[:booking][:room_id])
    @booking = Booking.new(booking_params)
    @user = @room.user
    @booking.user_id = current_user.id
    @booking.room_id = @room.id
    if @booking.invalid?
      render "rooms/show"
    else
      @days = (@booking.end_date - @booking.start_date).to_i
      @booking.total_price = (@room.fee * @booking.person * @days).to_i
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :person, :total_price, :room_id, :user_id )
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def new
    @room = Room.find(params[:booking][:room_id])
    @booking = Booking.new(booking_params)
    @days = (@booking.end_date - @booking.start_date).to_i
    @booking.total_price = (@room.fee * @booking.person * @days).to_i
    @booking.user_id = current_user.id
    @booking.room_id = @room.id
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id
    if @booking.save
      flash[:notice] = "新規予約を作成しました"
      redirect_to book_path(@booking)
    else 
      flash[:notice] = "新規予約に失敗しました"
      @room = Room.find(params[:booking][:room_id])
      @days = (@booking.end_date - @booking_start_date).to_i
      @booking.total_price = (@room.fee * @booking.person * @days).to_i
      @booking.user_id = current_user.id
      @booking.room_id = @room.id
      render "new"
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @room = @booking.room 
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :person, :total_price, :room_id, :user_id )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_q, only: [:index, :search]

  def index
    @user = User.find(current_user.id)
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "ルーム情報を新規登録しました"
      redirect_to room_path(@room)
    else
      render "new"
    end
  end

  def search
    @results = @q.result(distinct: true)
    if @q_header
      @results = @q_header.result(distinct: true)
    end
  end

  def show
    @room = Room.find(params[:id])
    @user = @room.user
    @booking = Booking.new
  end

  private
  def set_q
    @q = Room.ransack(params[:q])
  end
  
  def room_params
    params.require(:room).permit(:user_id, :room_image, :room_name, :description, :fee, :address)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
     session[:user_id] = user.id
     flash[:notice] = "ログインに成功しました"
     redirect_to user
    else
     flash.now[:alert] = "入力情報に間違いが含まれます、もう一度お願いします"
     render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "ようこそPOTE SHAREへ, #{@user.username} あなたのアカウントは無事に作成されました"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "更新が完了しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated room successfully deleted"
    redirect_to root_path
  end

  private 
  
  def user_params
    params.require(:user).permit(:username, :introduction, :email, :password, :password_confirmation, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  require 'carrierwave/processing/mini_magick'
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/confirm.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-6 offset-3 bg-light shadow">
      <div class="room_new_nav">
        <h4 class="book_new_check_descript">予約内容確認</h4>
        <h5 class="text-start mt-3"> ¥ <%= @room.fee %> / 日 </h5>
        <div class="room_show_date_select">
          <%= form_with model: @booking, local: true do |f| %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :start_date, value: @booking.start_date %>
            <%= f.hidden_field :end_date, value: @booking.end_date %>
            <%= f.hidden_field :person, value: @booking.person %>
            <%= f.hidden_field :total_price, value: @booking.total_price %>

            <p>開始日</p>
            <%= @booking.start_date %>

            <p>終了日</p>
            <%= @booking.end_date %>

            <p>使用日数 : <%= @days %>日</p>

            <p>人数: <%= @booking.person %>人</p>

            <p>合計金額</p>
            <%= @booking.total_price %>

            <p>上記内容でよろしければ「予約を確定」を押してください</p>

            <%= f.submit "予約を確定", class: "btn btn-primary form-control my-3" %>
            <%= f.submit "ルーム詳細に戻る", name: "back", class: "btn btn-dark form-control my-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container-fiuld">
  <h4>予約済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>ルーム画像</th>
        <th>ルーム名</th>
        <th>ルーム紹介</th>
        <th>合計料金</th>
        <th>開始日</th>
        <th>終了日</th>
        <th>予約確定日時</th>
    </thead>
    <tbody>
      <% if @booking == nil %>
        <p>予約済みの部屋はありません</p>
      <% end %>
      <% @bookings.each do |booking| %>
        <tr class="border-top">
          <% if booking.room.room_image? %>
            <td><%= link_to image_tag(booking.room.room_image.url, size:'50x50'), booking.room %></td>
          <% else %>
            <td><%= link_to image_tag("default_room.jpg", size:'50x50'), booking.room %></td>
          <% end %>
          <td><%= link_to booking.room.room_name, booking.room %></td>
          <td><%= booking.room.description %></td>
          <td><%= booking.total_price %></td>
          <td><%= booking.start_date %></td>
          <td><%= booking.end_date %></td>
          <td><%= booking.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bookings/new.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-6 offset-3 bg-light shadow">
      <div class="room_new_nav">
        <h4 class="book_new_check_descript">予約内容確認</h4>
        <h5 class="text-start mt-3"> ¥ <%= @room.fee %> / 日 </h5>
        <div class="room_show_date_select">
          <%= form_with model: @booking, local: true do |f| %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :start_date, value: @booking.start_date %>
            <%= f.hidden_field :end_date, value: @booking.end_date %>
            <%= f.hidden_field :person, value: @booking.person %>
            <%= f.hidden_field :total_price, value: @booking.total_price %>

            <p>開始日</p>
            <%= @booking.start_date %>

            <p>終了日</p>
            <%= @booking.end_date %>

            <p>使用日数 : <%= @days %>日</p>

            <p>人数: <%= @booking.person %>人</p>

            <p>合計金額</p>
            <%= @booking.total_price %>

            <p>上記内容でよろしければ「予約を確定」を押してください</p>

            <%= f.submit "予約を確定", class: "btn btn-primary form-control my-3" %>
            <%= link_to "ルーム詳細に戻る", room_path(@room), class: "form-control my-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container-fiuld">
  <div class="row">
    <div class="col-md-12">
      <div class="row">
        <label class="col-md-3">予約した部屋</label>
        <div class="col-md-9"><%= @room.room_name %></div>
      </div>
      <div class="row">
        <label class="col-md-3">開始日</label>
        <div class="col-md-9"><%= @booking.start_date %></div>
      </div>
      <div class="row">
        <label class="col-md-3">終了日</label>
        <div class="col-md-9"><%= @booking.end_date %></div>
      </div>
      <div class="row">
        <label class="col-md-3">価格</label>
        <div class="col-md-9"><%= @booking.total_price %></div>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="container room-show">
  <div class="row">
    <div class="col-6 offset-3 bg-light shadow">
      <div class="room_new_nav">
        <h4 class="book_new_check_descript">予約内容確認</h4>
        <h5 class="text-start mt-3"> ¥ <%= @room.fee %> / 日 </h5>
        <div class="room_show_date_select">
          <%= form_with model: @booking, url: new_book_path, local: true do |f| %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :start_date, value: @booking.start_date %>
            <%= f.hidden_field :end_date, value: @booking.end_date %>
            <%= f.hidden_field :person, value: @booking.person %>
            <%= f.hidden_field :total_price, value: @booking.total_price %>

            <p>開始日</p>
            <%= @booking.start_date %>

            <p>終了日</p>
            <%= @booking.end_date %>

            <p>使用日数 : <%= @days %>日</p>

            <p>人数: <%= @booking.person %>人</p>

            <p>合計金額</p>
            <%= @booking.total_price %>

            <p>上記内容でよろしければ「予約を確定」を押してください</p>

            <%= f.submit "予約を確定", class: "btn btn-primary form-control my-3" %>
            <%= link_to "ルーム詳細に戻る", room_path(@room), class: "form-control my-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark mt-auto py-3 bg-light" id="home-footer">
  <div class="container text-center">
    <span class="text-light">2023 POTEPAN.INC</span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success" role="alert">
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
  <div class="container-fluid">
    <%= link_to "Pote Share", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation" %>
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse me-1" id="navbarsExample04">
    <ul class="navbar-nav me-auto me-1 mb-md-0">
      <li class="nav-item">
        <%= search_form_for @q_header, url: search_rooms_path do |f| %>
          <%= f.search_field :address_or_room_name_cont, placeholder: 'キーワード検索' %>
          <%= f.submit '検索' %>
        <% end %>
      </li>
    </ul>
      <% if logged_in? %>
        <ul class="navbar-nav me-1 mb-md-0">
          <li class="nav-item me-1 mt-1">
          <div class="dorpdown">
          <button class="btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <% if current_user.profile_image? %>
              <%= image_tag current_user.profile_image.url(:icon), class: "rounded-circle" %>
            <% else %>
              <%= image_tag "default.png", alt: "メニュー", :size =>'100x100' %>
            <% end %>
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            <li><a class="dropdown-item" href="#"><%= link_to "ルーム登録", new_room_path, class: "dropdown-item"%></a></li>
            <li><a class="dropdown-item" href="#"><%= link_to "予約済みルーム一覧", bookings_path, class: "dropdown-item" %></a></li>
            <li><a class="dropdown-item" href="#"><%= link_to "登録済みルーム一覧", rooms_path, class: "dropdown-item" %></a></li>
            <li><a class="dropdown-item"><%= link_to "設定", user_path(current_user.id), class: "dropdown-item" %></a></li>
            <!--<li><a class="dropdown-item" href="#"><%= link_to "ログアウト", user_path(current_user.id), method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item" %></a></li>-->
            <li><a class="dropdown-item"><%= link_to "ログアウト", logout_path, class: "dropdown-item", method: :delete %><li>
          </ul>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav mb-md-0">
          <li class="nav-item me-1 mt-1">
            <%= link_to "Sign up", signup_path, class: "btn btn-info text-light" %>
          </li>
          <li class="nav-item me-1 mt-1">
            <%= link_to "ログイン", login_path, class: "btn btn-success" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShukuApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
      <%= render 'layouts/nav' %>
      <%= render 'layouts/messages' %>
  
      <%= yield %>
      <p class="flash-text"><%= flash.notice %></p>
			<p class="flash-text"><%= flash.alert %></p>
      <footer>
        <p>2023 POTEPAN.INC.</p>
      </footer>
      
    </div>
  </body>
</html>

app/views/pages/top.html.erb
<div class="bg-img">
  <div class="container" id="top-padding">
    <div class="col bg-light text-center p-4 p-sm-5 my-4 rounded">
      <h1 class="display-5" id="top-dis">Potepan Shareでまだ体験したことのない旅をしよう</h1>
      <hr class="my-4">
      <%= search_form_for @q_header, url: search_rooms_path do |f| %>
        <div class="row">
          <div class="col-md-10"><%= f.search_field :address_or_room_name_cont, placeholder: 'キーワード検索', class: "form-control" %></div>
          <div class="col"><%= f.submit '検索', class: "btn btn-outline-success" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <p class="display-6 mt-5" id="top-dis">おすすめのエリア</p>
    <div class="col-sm-6 col-md-3 card" id="top-card">
      <img class="img-fluid mt-4 card-img" src="<%= asset_pack_path 'media/images/tokyo.jpg' %>" >
      <div class="card-img-overlay">
        <p class="display-3 text-white" id="top-card-p"><%= link_to "東京", search_rooms_path(q:{address_cont:"東京"}), class: "top-link"%> </p>
      </div>
  　</div>
    <div class="col-sm-6 col-md-3 card" id="top-card">
    <img class="img-fluid mt-4 card-img" src="<%= asset_pack_path 'media/images/osaka.jpg' %>" >
      <div class="card-img-overlay">
        <p class="display-3 text-white" id="top-card-p"><%= link_to "大阪", search_rooms_path(q:{address_cont:"大阪"}), class: "top-link"%> </p>
      </div>
　  </div>
    <div class="col-sm-6 col-md-3 card" id="top-card">
      <img class="img-fluid mt-4 card-img" src="<%= asset_pack_path 'media/images/kyoto.jpg' %>" >
      <div class="card-img-overlay">
        <p class="display-3 text-white" id="top-card-p"><%= link_to "京都", search_rooms_path(q:{address_cont:"京都"}), class: "top-link"%> </p>
      </div>
　    </div>
    <div class="col-sm-6 col-md-3 card" id="top-card">
      <img class="img-fluid mt-4 card-img" src="<%= asset_pack_path 'media/images/sapporo.jpg' %>" >
      <div class="card-img-overlay">
        <p class="display-3 text-white" id="top-card-p"><%= link_to "札幌", search_rooms_path(q:{address_cont:"札幌"}), class: "top-link"%> </p>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="container-fiuld">
	<h4 class="pb-4">登録済みルーム一覧</h4>
	<table>
		<thead>
			<tr align="center">
				<th>ルーム画像</th>
				<th>ルーム名</th>
				<th>ルーム紹介</th>
				<th>料金</th>
				<th>作成日</th>
			</tr>
		</thead>
		<tbody>
			<% @rooms.each do |room| %>
				<tr class="border-top">
					<% if room.room_image? %>
						<td><%= link_to image_tag(room.room_image.url, size:'50x50'), room %></td>
					<% else %>
						<td><%= link_to image_tag("default_room.jpg", size:'50x50'), room %></td>
					<% end %>
					<td><%= link_to room.room_name, room %></td>
					<td><%= room.description %></td>
					<td><%= room.fee %></td>
					<td><%= room.created_at .to_s(:datetime_jp) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/rooms/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <h2 class="text-start mt-4">ルーム登録情報</h2>
      <%= render 'shared/errors', obj: @room %>
      <%= form_with(model: @room, class: "shadow p-3 mb-3 bg-light rounded", local: true) do |f| %>
        <div class="row mb-3 mt-3">
          <%= f.label :room_name, "ルーム名", class: "col-2 col-form-label text-dark" %></br>
          <div class="col-10">
            <%= f.text_field :room_name, class: "form-control shadow rounded", placeholder: "ルーム名を入力" %>
          </div>
        </div>

        <div class="row mb-3">
          <%= f.label :description, "ルーム紹介", class: "col-2 col-form-label text-dark" %></br>
          <div class="col-10">
            <%= f.text_area :description, class: "form-control shadow rounded", placeholder: "ルーム説明を入力" %>
          </div>
        </div>

        <div class="row mg-3">
          <%= f.label :fee, "料金", class: "col-2 col-form-label text-dark" %></br>
          <div class="col-10">
            <%= f.number_field :fee, class: "form-control shadow rounded", placeholder: "一日あたりの料金を入力" %>
          </div>
        </div>

        <div class="row mb-3 mt-3">
          <%= f.label :address, "住所", class: "col-2 col-form-label text-dark" %></br>
          <div class="col-10">
            <%= f.text_field :address, class: "form-control shadow rounded", placeholder: "住所を入力" %>
          </div>
        </div>

        <div class="row mb-3">
          <%= f.label :room_image, "ルーム画像", class: "col-2 col-form-label text-dark" %><br/>
          <div class="col-10">
            <%= f.file_field :room_image %>
          </div>
        </div>

        <div class="row mb-3">
          <div class="col" id="form-col-submit">
            <%= f.submit(@room.new_record? ? "登録" : "部屋情報編集", class: "btn btn-outline-dark btn-lg") %>
          </div>
        </div>

      <% end %>
    </div>
    
  </div>
</div>

app/views/rooms/show.html.erb
<div class="bg-light container room-show" >
  <div class="row">
    <div class="col-md-8">
      <% if @room.room_image? %>
        <%= image_tag @room.room_image.url, class: "room-show-image" %>
      <% else %>
        <%= image_tag "default_room.jpg", alt: "メニュー", class: "room-show-image-default" %>
      <% end %>

      <div class="room_show_detile" >
        <div class="room_show_detile_icon">
          <% if @user.profile_image.present? %>
            <%= image_tag @user.profile_image.url, class: "room_user_icon" %> 
          <% else %>
            <%= image_tag "/assets/default.png", class: "room_user_icon" %> 
          <% end %>
        </div>
        <div class="room_show_profile">
          <p class="room_show_profile_name"><%= @room.room_name %></p>
          <p class="room_show_profile_address">住所：<%= @room.address %></p>
        </div>
      </div>
      <p class="room_show_detile_description"><%= @room.description %></p>
    </div>
    <div class = "col-md-4">
      <div class="room_show_nav">
      <h5 class="text-start mt-3">¥ <%= @room.fee %> / 日</h5>
        <div class="room_show_date_select">
          <%= form_with(model: @booking, method: 'post', url: confirm_bookings_path, class: "shadow p-3 mb-3 bg-light rounded", local: true) do |f| %>
            <% if @booking.errors.any? %>
              <div class = "alert">
                <ul>
                  <% @booking.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <%= f.hidden_field :room_id, value: @room.id %>
            <%= f.hidden_field :user_id, value: current_user.id %>

            <%= f.label :start_date ,"開始日" %>
            <%= f.date_field :start_date, class: "form-control mb-4" %>

            <%= f.label :end_date ,"終了日" %>
            <%= f.date_field :end_date, class: "form-control mb-4" %>

            <%= f.label :person ,"人数" %>
            <%= f.number_field :person, class: "form-control mb-4" %>

            <% if logged_in? %>
              <%= f.submit "予約する", class: "btn btn-primary form-control" %>
            <% else %>
              <%= link_to "ログイン", login_path, class: "btn btn-success" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4" id="top-dis">プロフィール編集</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="flex-user">
	<div class="container pt-3 bg-light shadow rounded mt-5">
		<div class="row">
      <div class="col-md-10 offset-md-1">
        <h1 class="float-start mb-5" id="top-dis">アカウント(<%= @user.username %>)</h1>
          <table class="table">
            <tr>
              <th scope="row" id="top-dis">メールアドレス</th>
              <td><%= @user.email %></td>
            </tr>
            <tr>
              <th scope="row" id="top-dis">一言紹介</th>
              <td><%= @user.introduction %></td>
            </tr>
          </table>

      <div class="row align-items-center">
        <div class="col-3">
          <%= link_to "編集" , edit_user_path(@user), class: "btn btn-info text-light" %>
        </div>
      </div>
      </div>
		</div>
	</div>
</div>


<!--
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="shadow p-3 mb-3 bg-light rounded">
      <% if @user.profile_image? %>
        <%= image_tag @user.profile_image.url %>
      <% end %>
        <div class="row mb-3 mt-3">
          <label class: "col-2 col-form-label text-dark" id="top-dis">ユーザー名
            <p id="top-dis"><%= @user.username %></p>
          </lable>
          <div class="col-10">
            
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %>
  </div>
<% end %>
-->